version: "3.9"

services:
  database_service:
    image: postgres
    container_name: database_service
    restart: always
    ports: 
      - 3000:3000
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: api-cars-s.o.l.i.d
    restart: always
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app


volumes:
  pgdata:
    driver: local
